import '../../domain/entities/emergency_event.dart';

class EmergencyModel extends EmergencyEvent {
  const EmergencyModel({
    required super.id,
    required super.userId,
    required super.latitude,
    required super.longitude,
    required super.status,
    required super.createdAt,
  });

  factory EmergencyModel.fromJson(Map<String, dynamic> json) {
    return EmergencyModel(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      latitude: (json['latitude'] as num?)?.toDouble() ?? 0.0,
      longitude: (json['longitude'] as num?)?.toDouble() ?? 0.0,
      status: json['status'] as String? ?? 'PENDING',
      createdAt: json['created_at'] != null 
          ? DateTime.parse(json['created_at'] as String) 
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    // Return map for inserts (id and created_at auto-generated by PostgreSQL)
    return {
      'user_id': userId,
      'latitude': latitude,
      'longitude': longitude,
      'status': status,
    };
  }

  factory EmergencyModel.fromEntity(EmergencyEvent entity) {
    return EmergencyModel(
      id: entity.id,
      userId: entity.userId,
      latitude: entity.latitude,
      longitude: entity.longitude,
      status: entity.status,
      createdAt: entity.createdAt,
    );
  }
}
