import 'package:flutter/foundation.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import '../constants/constants.dart';

class GeminiService {
  final GenerativeModel? _model;

  GeminiService()
      : _model = AppConstants.geminiApiKey.isNotEmpty
            ? GenerativeModel(
                model: 'gemini-1.5-flash',
                apiKey: AppConstants.geminiApiKey,
              )
            : null;

  /// Sends a query prompt to the Gemini Generative Model.
  /// Falls back to smart rule engine responses if key is unconfigured or fails.
  Future<String> queryGemini(String prompt) async {
    if (_model == null) {
      debugPrint('Gemini API Key missing. Falling back to offline first-aid mock database.');
      return _generateOfflineMockResponse(prompt);
    }

    try {
      final content = [Content.text(prompt)];
      final response = await _model.generateContent(content);
      return response.text ?? 'No response was generated by the AI assistant.';
    } catch (e) {
      debugPrint('Gemini client error: $e. Using offline mock guidelines.');
      return _generateOfflineMockResponse(prompt);
    }
  }

  String _generateOfflineMockResponse(String query) {
    final queryLower = query.toLowerCase();

    if (queryLower.contains('earthquake') || queryLower.contains('भूकम्प')) {
      return '''
**भूकम्प सुरक्षा मार्गदर्शन (Earthquake Safety Guidelines):**
1. **Drop, Cover, and Hold On!** तुरुन्तै भुइँमा निहुरिनुहोस्, बलियो टेबल मुनि ओत लाग्नुहोस् र टेबलको खुट्टा दह्रोसँग समात्नुहोस्।
2. अग्ला सामान, झ्याल, र भित्ताहरूबाट टाढा रहनुहोस्।
3. घरभित्र हुनुहुन्छ भने भूकम्प नसकिन्जेल भित्रै बस्नुहोस्। लिफ्ट प्रयोग नगर्नुहोस्।
4. खुला क्षेत्रमा हुनुहुन्छ भने विजुलीका खम्बाहरू, रूखहरू र भवनहरूबाट टाढा रहनुहोस्।
''';
    } else if (queryLower.contains('snake') || queryLower.contains('सर्प') || queryLower.contains('bite')) {
      return '''
**सर्पदंश प्राथमिक उपचार (Snake Bite First Aid):**
1. पीडित व्यक्तिलाई शान्त राख्नुहोस्। हलचल गर्दा विष शरीरमा छिटो फैलिन्छ।
2. टोकेको भागलाई मुटुको सतह भन्दा तल राख्नुहोस्।
3. टोकेको घाउ वरिपरिका कसिलो लुगा वा गहनाहरू तुरुन्तै फुकाल्नुहोस्।
4. **घाउ काट्ने वा घाउमा विष चुस्ने काम कदापि नगर्नुहोस्!**
5. घाउमा सफा पट्टी खुकुलो गरी बाँध्नुहोस् र तुरुन्तै नजिकैको विष उपचार केन्द्र लैजानुहोस्।
''';
    } else if (queryLower.contains('bleeding') || queryLower.contains('रगत') || queryLower.contains('cut')) {
      return '''
**रक्तस्राव नियन्त्रण (Bleeding First Aid Control):**
1. घाउ भएको ठाउँमा सफा कपडा वा पट्टीले सिधा दबाब (Direct Pressure) दिनुहोस्।
2. सम्भव भएसम्म रगत बगेको अंगलाई मुटुको सतह भन्दा माथि उठाउनुहोस् (Elevate)।
3. दबाब दिइरहेको कपडा रगतले भिजेमा, त्यसलाई नफुकाली माथिबाट अर्को कपडा थप्नुहोस्।
4. पीडितलाई न्यानो राख्नुहोस् र तत्कालै अस्पताल पुर्‍याउनुहोस्।
''';
    } else if (queryLower.contains('fire') || queryLower.contains('आगो') || queryLower.contains('burn')) {
      return '''
**आगलागी सुरक्षा र उपचार (Fire & Burn Care Guidelines):**
1. कोठामा धुवाँ फैलिएमा घुँडा टेकेर वा लसपसिएर ढोकातर्फ जानुहोस्। धुवाँ माथि बढी हुन्छ।
2. यदि कपडामा आगो सल्किएमा: **Stop, Drop, and Roll!** (उभिनुहोस्, भुइँमा लड्नुहोस्, र गुड्नुहोस्)।
3. जलेको घाउमा तुरुन्तै १०-१५ मिनेट सफा र चिसो पानी खन्याउनुहोस्। बरफ वा मलम नलगाउनुहोस्।
4. फोकाहरू फुटाउने नगर्नुहोस् र अस्पताल लैजानुहोस्।
''';
    } else {
      return '''
नमस्ते, म सुरक्शा नेपालको AI आपतकालीन सहायक हुँ। म तपाईंलाई विपद् सुरक्षा, प्राथमिक उपचार, र आपतकालीन मार्गनिर्देशन दिन सक्छु।

तपाईं निम्न विषयहरूमा सोध्न सक्नुहुन्छ:
* **भूकम्पको बेला के गर्ने? (Earthquake safety)**
* **सर्पले टोक्दा गरिने प्राथमिक उपचार (Snake bite care)**
* **रगत बग्दा नियन्त्रण गर्ने उपाय (How to stop bleeding)**
* **आगलागीमा बच्ने तरिकाहरू (Fire emergency guidance)**
''';
    }
  }
}
